dscnitrourkela/project-dates

- .all-contributorsrc
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
- Setup License with MIT License
- Setup contribution guidelines for detailed workflow
- Add the all-contributor bot to recognise all contributors. Link: https://allcontributors.org/
- Add Starware to README to encourage people to star the repo
- Add code of conduct to maintain the integrity
- Issue Templates
This PR closes #26
> Add License, Contributor Guides, Code of Conduct, all-contributors bot 

- .firebaserc
- firebase.json
- functions/.gitignore
- functions/index.js
- functions/package-lock.json
- functions/package.json
- sources/index.js
- created a trigger based cloud function for setting custom claim
- the cloud function is triggered on signup
- deployed to GCP and ready to use
> Set default custom claim role via cloud function

- .gitignore
- sources/datasources/users.js
- sources/index.js
- sources/models/user.js
- sources/resolvers/user.js
- sources/schema/user.js
- sources/seed_database.js
- signin/signup API
- NITR verification complete
- remove mongoose warnings
- remove unwanted comments on user datasources
> Authentication Flow

- sources/.env.example
- sources/index.js
- sources/package-lock.json
- sources/package.json
- created an account with elaichi gmail
- initialised cloudinary SDK
- ready to upload media
> setup cloudinary for media management

- sources/datasources/accessLevels.js
- sources/datasources/clubs.js
- sources/datasources/events.js
- sources/datasources/stories.js
- sources/errors/index.js
- sources/helpers/apollo.js
- sources/helpers/permissions.js
- sources/index.js
- sources/models/club.js
- sources/models/currentStory.js
- sources/models/event.js
- sources/package-lock.json
- sources/package.json
- sources/resolvers/accessLevel.js
- sources/resolvers/club.js
- sources/resolvers/mutation.js
- sources/resolvers/story.js
- sources/resolvers/user.js
- sources/schema/accessLevel.js
- sources/schema/club.js
- sources/schema/event.js
- sources/schema/story.js
- sources/schema/user.js
This PR includes
- Fix errors after Deploying
- Separated Access Level CRUD operation from Update Club
- Ensure all API are consistent in terms of responses and error codes
- Complete Add Club API for clubs onboarding with all necessary properties
below is the finalised schema for clubs.
```
{
clubName: String,
memberAccess: [AcessLevel],
facAd: String,
logo: String,
events: [Event],
society: String,
domain: String,
links: String,	
backgroundColor: String, 
contactInfo: [{ 
name: String,
designation: String,
mobileNo: String,
email: String
}
```
Fixes #
#61
> Hotfix+Refactoring

- sources/datasources/accessLevels.js
- sources/datasources/clubs.js
- sources/datasources/events.js
- sources/datasources/users.js
- sources/datasources/venues.js
Upgrade deprecated remove to deleteOne() in all collections
> Fix deprecated remove method in delete operations

- sources/apollo/server.js
- sources/apollo/users/user.datasources.js
- sources/helpers/firebase.js
- sources/helpers/permissions.js
- sources/package-lock.json
This PR contains the folllowing
- delete user object from firebase
- handle outdated JWT with old mongoID
**Notes**
A maximum call stack size error was thrown when requesting for clubAccess in a user sign up.
This problem was arising becuase, the clubAccess was already populated in the create user code of datasource and apollo was trying to resolve the already populated field which caused the stack size to exceed. Presently, to avoid this, we have made sure not to send in populated nested fields which works for now. But if one thinks about it, since its already populated, the field resolver needs to be smart enough not to populate it again.
This issue https://github.com/dscnitrourkela/project-dates/issues/79 is not fixed in this PR
> fix auth user flow

- .github/workflows/gcp-deploy.yml
Linked Issue that will be closed by this: #83 
❤️Thank you!
> Update Actions to run on push to development

- sources/ecosystem.config.js
- sources/package.json
Setup restart strategy to make sure that PM2 restart does not go into a loop in cases when an error happens
Reference: https://pm2.keymetrics.io/docs/usage/restart-strategies/
❤️Thank you!
> Update PM2 scripts

- sources/helpers/apollo.js
- sources/helpers/permissions.js
Add `superuser.all` permission to level 5
> add superuser permissiont to level 5

- sources/.prettierrc
- sources/apollo/mess/mess.datasource.js
- sources/apollo/mess/mess.model.js
- sources/apollo/mess/mess.resolver.js
- sources/apollo/mess/mess.schema.js
- sources/apollo/resolvers.js
- sources/apollo/schema.js
- sources/apollo/server.js
Earlier
prettier used to wrap single arguments of arrow function within parens, whereas ESLint recommended against
New Setting
prettier and ESlint both recommended no parens for the single argument arrow function
Discussions: #88
The resolver flattens the data to make the query and response easier to parse on client-side
Further scope
1. Add filter for veg
2. Write Operations
API Flow for client side
1. Call the get mess list query to get list of mess and their IDs
2. Get the menu by IDs
Note: The above query(1) does not support resolve by ID by design as
there was no use case found that needs all menu of all mess in single query
❤️Thank you!
> Setup Mess Menu

- sources/.dockerignore
- sources/.env.example
- Adds pm2 env's in env.example
- removes unused env's
- Adds test folder in dockerignore
❤️Thank you!
> chore: Updates .env example and .dockerignore

- api/.dockerignore
> feat: Adds dockerignore

- api/graphql/resolvers.js
- api/graphql/scalars.js
- api/graphql/server.js
- api/graphql/typeDefs.js
- api/package.json
- api/yarn.lock
- Add Date mock
- Add graphql-iso-date package for date time
❤️Thank you!
> Add DateTime Type

- api/src/apollo/Org/index.ts
- api/src/apollo/Org/mutations.ts
- api/src/apollo/Org/queries.ts
- api/src/apollo/Org/type.ts
- api/src/apollo/index.ts
- api/src/apollo/scalers.ts
- api/src/prisma/schema.prisma
- create org prisma model
- create org type and corresponding enums
- create org queries and mutations
> feat: create organisation model

- api/src/constants/auth.ts
- api/src/constants/index.ts
- api/src/helpers/auth/checkPermissions.ts
- api/src/helpers/errorClass/authError.ts
- api/src/helpers/errorClass/index.ts
- api/src/helpers/index.ts
- api/src/rest/controller/auth/get.ts
- api/src/rest/controller/auth/update.ts
- api/src/rest/routes/auth.ts
> feat: Adds Authorisation

- .github/workflows/deploy.yml
- api/Dockerfile
> Deployment setup

- api/Dockerfile
> feat: Add dev dependecies for temporary use

- api/src/apollo/DeveloperInfo/queries.ts
- api/src/config/nexus.ts
- api/src/helpers/auth/checkPermissions.ts
- api/src/helpers/auth/verify.ts
- api/src/utils/context.ts
> feat: Authenticates a sample query

- api/src/apollo/DeveloperInfo/queries.ts
- api/src/config/firebase.ts
- api/src/rest/controller/instamojo/payment.ts
> fix: update the parameters sent via request body

- api/src/apollo/server.ts
> remove: extra pr

- api/src/rest/routes/health.ts
> change get to post route

- api/src/rest/controller/base/index.ts
- api/src/rest/controller/base/zimbra.ts
- api/src/rest/routes/health.ts
> fix: create zimbra authentication route

- api/src/apollo/server.ts
- api/src/prisma/schema.prisma
- api/src/rest/controller/base/user.ts
- api/src/rest/controller/instamojo/webhook.ts
> fix: resolve all issues

- api/src/apollo/User/mutations.ts
- api/src/apollo/server.ts
- api/src/prisma/schema.prisma
> fix: update mobile property for users

- api/src/rest/controller/base/zimbra.ts
> fix: Zimbra API Call failing

- api/src/rest/controller/base/user.ts
> fix: NITR not getting registered

- api/src/rest/controller/base/event.ts
- api/src/rest/routes/health.ts
> fix: add existing registration check

- .github/workflows/deploy.yml
> Ts build fix

- api/src/apollo/server.ts
> fix: shows graphql endpoint on production

- api/src/apollo/Event/queries.ts
- api/src/apollo/EventRegistration/queries.ts
- api/src/apollo/Org/queries.ts
- api/src/apollo/Scalars/Pagination.ts
- api/src/apollo/Scalars/index.ts
- api/src/apollo/Story/queries.ts
- api/src/apollo/Transaction/queries.ts
- api/src/apollo/User/queries.ts
- api/src/helpers/auth/checkPermissions.ts
> fix: add pagination for all heavy queries

- api/src/rest/model/permissions.ts
> fix: remove unused umid

- api/src/apollo/User/mutations.ts
- api/src/apollo/User/type.ts
> fix: small change

- api/src/rest/controller/base/event.ts
> fix: update event types according to NU

- api/src/apollo/Event/mutations.ts
- api/src/apollo/Org/queries.ts
- api/src/config/nexus.ts
- api/src/rest/controller/auth/get.ts
- api/src/rest/controller/auth/update.ts
- api/src/rest/controller/base/event.ts
- api/src/rest/controller/base/health.ts
- api/src/rest/controller/instamojo/payment.ts
- api/src/rest/routes/health.ts
- api/src/rest/server.ts
> feat: add status argument to org

- api/.vscode/settings.json
- api/src/apollo/Event/mutations.ts
- api/src/apollo/Event/type.ts
- api/src/prisma/schema.prisma
- api/src/rest/controller/base/event.ts
- api/src/rest/controller/instamojo/webhook.ts
* change organisation in instamojo webhook
* change schema of event
❤️Thank you!
> feat: setup for innovision

- api/src/rest/controller/base/event.ts
> fix: spelling in events

- api/src/rest/controller/base/event.ts
> fix: events fetch

- api/src/rest/controller/base/event.ts
- api/src/rest/controller/base/user.ts
- api/src/rest/controller/instamojo/webhook.ts
> chore: change organisation to innovision

- api/src/apollo/Event/mutations.ts
- api/src/apollo/Event/type.ts
- api/src/apollo/Transaction/queries.ts
- api/src/apollo/User/queries.ts
- api/src/prisma/schema.prisma
- Adds rules to events
Fixes #156
> feat: add rules to events

- api/src/apollo/TeamRegistration/mutation.ts
- api/src/apollo/TeamRegistration/queries.ts
- api/src/apollo/TeamRegistration/type.ts
- api/src/prisma/schema.prisma
- added grades in teamRegistration type
- added grades field in mutation
❤️Thank you!
> feat: added grades field to team-registrations

- .vscode/settings.json
- api/package.json
- api/src/apollo/Event/mutations.ts
- api/src/apollo/Event/queries.ts
- api/src/apollo/Event/type.ts
- api/src/apollo/EventRegistration/queries.ts
- api/src/apollo/Institute/index.ts
- api/src/apollo/Institute/mutations.ts
- api/src/apollo/Institute/queries.ts
- api/src/apollo/Institute/type.ts
- api/src/apollo/Org/mutations.ts
- api/src/apollo/Org/queries.ts
- api/src/apollo/Org/type.ts
- api/src/apollo/User/mutations.ts
- api/src/apollo/User/queries.ts
- api/src/apollo/User/type.ts
- api/src/prisma/schema.prisma
> chore: code for innovison'24 

- api/src/apollo/Org/mutations.ts
- api/src/apollo/User/mutations.ts
> feat: increase num of registrations for college
